--liquibase formatted sql
--changeset {authorName}:{id}

delete from `dm_obj_attribute_dtl` where id in(41,42,43,44,45);

insert into `dm_obj_attribute_dtl` (`ID`, `CURRENT_OBJECT_ID`, `COLLECTION_DATA_TYPE`, `DATA_FORMATOR_KEY`, `TYPE`, `DECIMAL_PLACES`, `DELIMITER_KEY`,`ATTRIBUTE_HEADER_NAME`, `IS_BO_ATTRIBUTE`, `IS_REQUIRED`, `IS_REVERSE_VALUE_USED`, `isXMLAttribute`, `MAX_LENGTH`, `MAX_VALUE`, `MIN_VALUE`, `ATTRIBUTE_NAME`, `PARENT_OBJECT_ID`, `SAMPLE_VALUE`, `SEQUENCE_NUMBER`, `XML_TAG_NAME`)
values('41',NULL,NULL,NULL,'java.lang.String','-1',NULL,'Action','0','1',NULL,NULL,'32',NULL,NULL,'dlAction','3','Add','0','1');
insert into `dm_obj_attribute_dtl` (`ID`, `CURRENT_OBJECT_ID`, `COLLECTION_DATA_TYPE`, `DATA_FORMATOR_KEY`, `TYPE`, `DECIMAL_PLACES`, `DELIMITER_KEY`, `ATTRIBUTE_HEADER_NAME`, `IS_BO_ATTRIBUTE`, `IS_REQUIRED`, `IS_REVERSE_VALUE_USED`, `isXMLAttribute`, `MAX_LENGTH`, `MAX_VALUE`, `MIN_VALUE`, `ATTRIBUTE_NAME`, `PARENT_OBJECT_ID`, `SAMPLE_VALUE`, `SEQUENCE_NUMBER`, `XML_TAG_NAME`)
values('42',NULL,NULL,NULL,'java.lang.String','-1',NULL,'Reference Number','1','1',NULL,NULL,'255',NULL,NULL,'referenceNumber','3','NC25','1','1');
insert into `dm_obj_attribute_dtl` (`ID`, `CURRENT_OBJECT_ID`, `COLLECTION_DATA_TYPE`, `DATA_FORMATOR_KEY`, `TYPE`, `DECIMAL_PLACES`, `DELIMITER_KEY`, `ATTRIBUTE_HEADER_NAME`, `IS_BO_ATTRIBUTE`, `IS_REQUIRED`, `IS_REVERSE_VALUE_USED`, `isXMLAttribute`, `MAX_LENGTH`, `MAX_VALUE`, `MIN_VALUE`, `ATTRIBUTE_NAME`, `PARENT_OBJECT_ID`, `SAMPLE_VALUE`, `SEQUENCE_NUMBER`, `XML_TAG_NAME`) 
values('43',NULL,NULL,NULL,'java.lang.String','-1',NULL,'Sr. No.','1','1',NULL,NULL,'255',NULL,NULL,'srNo','3','11','2','1');
insert into `dm_obj_attribute_dtl` (`ID`, `CURRENT_OBJECT_ID`, `COLLECTION_DATA_TYPE`, `DATA_FORMATOR_KEY`, `TYPE`, `DECIMAL_PLACES`, `DELIMITER_KEY`, `ATTRIBUTE_HEADER_NAME`, `IS_BO_ATTRIBUTE`, `IS_REQUIRED`, `IS_REVERSE_VALUE_USED`, `isXMLAttribute`, `MAX_LENGTH`, `MAX_VALUE`, `MIN_VALUE`, `ATTRIBUTE_NAME`, `PARENT_OBJECT_ID`, `SAMPLE_VALUE`, `SEQUENCE_NUMBER`, `XML_TAG_NAME`) 
values('44',NULL,NULL,NULL,'java.lang.String','-1',NULL,'Template Name','1','0',NULL,NULL,'255',NULL,NULL,'templateName','3','KARVY','3','1');
insert into `dm_obj_attribute_dtl` (`ID`, `CURRENT_OBJECT_ID`, `COLLECTION_DATA_TYPE`, `DATA_FORMATOR_KEY`, `TYPE`, `DECIMAL_PLACES`, `DELIMITER_KEY`, `ATTRIBUTE_HEADER_NAME`, `IS_BO_ATTRIBUTE`, `IS_REQUIRED`, `IS_REVERSE_VALUE_USED`, `isXMLAttribute`, `MAX_LENGTH`, `MAX_VALUE`, `MIN_VALUE`, `ATTRIBUTE_NAME`, `PARENT_OBJECT_ID`, `SAMPLE_VALUE`, `SEQUENCE_NUMBER`, `XML_TAG_NAME`) 
values('45',NULL,NULL,NULL,'java.lang.String','-1',NULL,'Field Name','1','0',NULL,NULL,'255',NULL,NULL,'fieldNameHeader','3','','4','1');
insert into `dm_obj_attribute_dtl` (`ID`, `CURRENT_OBJECT_ID`, `COLLECTION_DATA_TYPE`, `DATA_FORMATOR_KEY`, `TYPE`, `DECIMAL_PLACES`, `DELIMITER_KEY`, `ATTRIBUTE_HEADER_NAME`, `IS_BO_ATTRIBUTE`, `IS_REQUIRED`, `IS_REVERSE_VALUE_USED`, `isXMLAttribute`, `MAX_LENGTH`, `MAX_VALUE`, `MIN_VALUE`, `ATTRIBUTE_NAME`, `PARENT_OBJECT_ID`, `SAMPLE_VALUE`, `SEQUENCE_NUMBER`, `XML_TAG_NAME`) 
values('46',NULL,NULL,NULL,'java.lang.String','-1',NULL,'Key Name','1','1',NULL,NULL,'255',NULL,NULL,'fieldName','3','','5','1');
insert into `dm_obj_attribute_dtl` (`ID`, `CURRENT_OBJECT_ID`, `COLLECTION_DATA_TYPE`, `DATA_FORMATOR_KEY`, `TYPE`, `DECIMAL_PLACES`, `DELIMITER_KEY`, `ATTRIBUTE_HEADER_NAME`, `IS_BO_ATTRIBUTE`, `IS_REQUIRED`, `IS_REVERSE_VALUE_USED`, `isXMLAttribute`, `MAX_LENGTH`, `MAX_VALUE`, `MIN_VALUE`, `ATTRIBUTE_NAME`, `PARENT_OBJECT_ID`, `SAMPLE_VALUE`, `SEQUENCE_NUMBER`, `XML_TAG_NAME`) 
values('47',NULL,NULL,NULL,'java.lang.String','-1',NULL,'Field Value in Template','1','0',NULL,NULL,'255',NULL,NULL,'fieldValue','3','Ram Kumar','6','1');
