--liquibase formatted sql
--changeset {authorName}:{id}
delete from rtatemplates where id>0;

insert into `rtatemplates` (Name,TemplateType,TemplateName) values('KARVY FINTECH PVT. LTD, BANGALORE','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('LINK INTIME INDIA PVT. LTD, MUMBAI','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('CAMEO CORPORATE SERVICES LTD, CHENNAI','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('HOUSING DEVELOPMENT FINANCE CORP.LTD.','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('KARVY FINTECH PVT. LTD, HYDERABAD2','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('LINK INTIME INDIA PVT. LTD, AHMEDABAD3','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('KARVY FINTECH PVT. LTD, KOLKATA2','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('R&D INFOTECH PVT. LTD, KOLKATA1','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('INTEGRATED ENTERPRISES (INDIA) LTD, BANGALORE','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('LINK INTIME INDIA PVT. LTD, KOLKATA','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('ZUARI INVESTMENTS LTD, DELHI','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('C B MANAGEMENT SERVICES PVT. LTD, KOLKATA','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('DATAMATICS BUSINESS SOLUTIONS LTD, MUMBAI2','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('MCS LTD, DELHI','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('DATAMATICS BUSINESS SOLUTIONS LTD, MUMBAI3','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('TSR DARASHAW LTD, MUMBAI','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('BIGSHARE SERVICES PVT. LTD, HYDERABAD','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('KARVY FINTECH PVT. LTD, HYDERABAD3','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('BEETAL FINANCIAL & COMPUTER SERVICES PVT. LTD, DELHI2','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('COMPUTECH SHARECAP LTD, MUMBAI','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('ALANKIT ASSIGNMENTS LTD, NEW DELHI5','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('LINK INTIME INDIA PVT. LTD, DELHI1','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('S.K.D.C. CONSULTANTS LTD, COIMBATORE','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('SHAREX DYNAMIC (INDIA) PVT. LTD, MUMBAI2','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('THE RAMCO CEMENTS LIMITED','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('MAS SERVICES LTD, DELHI','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('MRF LTD.','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('ALANKIT ASSIGNMENTS LTD, NEW DELHI1','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('KARVY FINTECH PVT. LTD, HYDERABAD (RELIANCE INDUSTRIES LTD.)','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('RCMC SHARE REGISTRY PVT. LTD, DELHI','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('INTEGRATED ENTERPRISES (INDIA) LTD, CHENNAI1','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('ACC LTD.','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('HINDALCO INDUSTRIES LTD.','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('INTEGRATED ENTERPRISES (INDIA) LTD, CHENNAI2','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('BHARAT FORGE LTD.','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('KARVY FINTECH PVT. LTD, HYDERABAD (ESCORTS LTD.)','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('DATA SOFTWARE RESEARCH COMPANY PVT. LTD, CHENNAI1','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('GUJARAT NARMADA VALLEY FERTILIZERS & CHEMICALS LTD.','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('LINK INTIME INDIA PVT. LTD, VADODARA1','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('KARVY FINTECH PVT. LTD, HYDERABAD1','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('INDIAN HOTELS CO.LTD.','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('ITC LTD.','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('APOLLO TYRES LTD.','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('KARVY FINTECH PVT. LTD, MUMBAI1','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('LINK INTIME INDIA PVT. LTD, DELHI3','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('BIGSHARE SERVICES PVT. LTD, MUMBAI1','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('CANBANK COMPUTER SERVICES LTD, BENGALURU','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('MCS LTD, MUMBAI1','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('ALANKIT ASSIGNMENTS LTD, NEW DELHI2','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('LINK INTIME INDIA PVT. LTD, PUNE','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('AARTHI CONSULTANTS PVT. LTD, HYDERABAD','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('MAHESHWARI DATAMATICS PVT LTD, KOLKATA1','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('3I INFOTECH LTD, MUMBAI','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('MCS LTD, AHMEDABAD1','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('BTS CONSULTANCY SERVICES PVT. LTD, CHENNAI','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('SUNDARAM-CLAYTON LTD, CHENNAI','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('MCS LTD, MUMBAI2','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('PURVA SHARE REGISTRY (INDIA) PVT. LTD, MUMBAI2','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('MAHESHWARI DATAMATICS PVT LTD, KOLKATA2','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('FREEDOM REGISTRY LTD, NASHIK','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('LINK INTIME INDIA PVT. LTD, AHMEDABAD1','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('LINK INTIME INDIA PVT. LTD, COIMBATORE','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('ALANKIT ASSIGNMENTS LTD, KOLKATA','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('BIGSHARE SERVICES PVT. LTD, MUMBAI2','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('VENTURE CAPITAL & CORPORATE INVESTMENTS PVT. LTD, HYDERABAD','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('LINK INTIME INDIA PVT. LTD, DELHI2','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('RCMC SHARE REGISTRY PVT. LTD, NOIDA','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('ESAB INDIA LTD.','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('SKYLINE FINANCIAL SERVICES PVT. LTD, DELHI','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('S. K. INFOSOLUTIONS PVT. LTD, KOLKATA','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('XL SOFTECH SYSTEMS LTD, HYDERABAD','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('SHAREX DYNAMIC (INDIA) PVT. LTD, MUMBAI1','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('ALANKIT ASSIGNMENTS LTD, NEW DELHI3','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('KARVY FINTECH PVT. LTD, HYDERABAD (MAHARASHTRA SCOOTERS LTD.)','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('MCS LTD, KOLKATA2','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('SARTHAK GLOBAL LTD, INDORE','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('EIH LTD, KOLKATA','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('UNIVERSAL CAPITAL SECURITIES PVT. LTD, MUMBAI','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('ADROIT CORPORATE SERVICES PVT. LTD, MUMBAI','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('PRAKASH INDUSTRIES LTD.','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('DATAMATICS BUSINESS SOLUTIONS LTD, MUMBAI1','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('ABHIPRA CAPITAL LTD, NEW DELHI','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('DATA SOFTWARE RESEARCH COMPANY PVT. LTD, CHENNAI2','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('NICHE TECHNOLOGIES PVT. LTD, KOLKATA1','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('INTEGRATED ENTERPRISES (INDIA) LTD, KERALA','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('ANKIT CONSULTANCY PVT. LTD, INDORE1','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('GNSA INFOTECH LTD, CHENNAI1','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('AVT NATURAL PRODUCTS LTD.','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('MCS LTD, VADODARA','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('EIH LTD, DELHI','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('GUJARAT AMBUJA EXPORTS LTD.','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('CIL SECURITIES LTD, HYDERABAD','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('SANGHI INDUSTRIES LTD.','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('KARVY FINTECH PVT. LTD, DELHI','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('JAYKAY ENTERPRISES LTD, KANPUR','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('INDIAN METALS & FERRO ALLOYS LTD.','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('ABS CONSULTANT PVT. LTD, KOLKATA1','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('SANWARIA CONSUMER LTD-','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('BIGSHARE SERVICES PVT. LTD, AHMEDABAD','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('NICHE TECHNOLOGIES PVT. LTD, KOLKATA3','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('MCS LTD, KOLKATA1','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('NICHE TECHNOLOGIES PVT. LTD, KOLKATA2','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('ANKIT CONSULTANCY PVT. LTD, INDORE2','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('KARVY FINTECH PVT. LTD, MUMBAI2','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('SATELLITE CORPORATE SERVICES PVT LTD, MUMBAI2','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('MCS LTD, AHMEDABAD2','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('INDUS PORTFOLIO PVT. LTD, DEHLI','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('SKYLINE FINANCIAL SERVICES PVT. LTD, MUMBAI','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('SATELLITE CORPORATE SERVICES PVT LTD, MUMBAI1','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('LINK INTIME INDIA PVT. LTD, AHMEDABAD2','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('ABS CONSULTANT PVT. LTD, KOLKATA2','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('BGSE FINANCIAL LTD, BANGALORE','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('SYSTEM SUPPORT SERVICES, MUMBAI','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('MCS LTD, KOLKATA3','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('GNSA INFOTECH LTD, CHENNAI2','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('BIGSHARE SERVICES PVT. LTD, GUJARAT','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('ADROIT CORPORATE SERVICES PVT. LTD, VADODARA','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('MCS LTD, KOLKATA4','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('R&D INFOTECH PVT. LTD, KOLKATA2','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('LINK INTIME INDIA PVT. LTD, VADODARA2','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('INTEGRATED ENTERPRISES (INDIA) LTD, COCHIN','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('CIL SECURITIES LTD.','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('SHAREPRO SERVICES (INDIA) PVT. LTD, AHMEDABAD','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('BEETAL FINANCIAL & COMPUTER SERVICES PVT. LTD, DELHI1','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('TCFC FINANCE LTD.','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('ALANKIT ASSIGNMENTS LTD, NEW DELHI6','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('RAJAPALAYAM MILLS LTD.-','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('BIGSHARE SERVICES PVT. LTD, DELHI','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('URVA SHAREGISTRY (INDIA) PVT. LTD, MUMBAI','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('MAGELLANIC CLOUD LTD','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('ABC COMPUTERS PVT. LTD, KOLKATA','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('JAGATJIT INDUSTRIES LTD.','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('THE INDIAN HOTELS COMPANY LTD, MUMBAI','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('KARVY FINTECH PVT. LTD, KOLKATA1','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('ACCURATE SECURITIES & REGISTRY PVT. LTD, GUJARAT','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('PURVA SHARE REGISTRY (INDIA) PVT. LTD, MUMBAI1','RTA Letter','Client Agreement With Adhyata.docx');
insert into `rtatemplates` (Name,TemplateType,TemplateName) values('ALANKIT ASSIGNMENTS LTD, NEW DELHI4','RTA Letter','Client Agreement With Adhyata.docx');


